Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "public_network"
  config.vm.network "forwarded_port", guest: 80, host: 9091
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"  
    vb.cpus = 2         
  end
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
  end
  
end
